function cellInfo = bus_SL_IN(varargin) 
% BUS_SL_IN returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

% Lucas Jürgens (BA), lucas.juergens@zubox.de, 2017-02
% Moritz Schappler, schappler@irt.uni-hannover.de
% (C) Institut für Regelungstechnik, Universität Hannover

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'SL_IN_type', ... 
    'SL_func.h', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'state', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'param_D', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'param_K', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'q_set', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'qd_set', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'realsense_imu', 6, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'FMext', 6, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ft_meas_mini40', 6, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ... 
{'realsense_acc', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ... 
{'realsense_gyro', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ... 
} ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
